[[main]]
  identifier = "docs"
  name = "Docs"
  url = "docs"
  weight = 1

[[main]]
  identifier = "Notes"
  name = "Notes"
  url = "notes"
  weight = 2

[[main]]
  identifier = "Acknowledgements"
  name = "Acknowledgements"
  url = "acknowledgements"
  weight = 4


[[main]]
  identifier = "blog"
  name = "Blog"
  url = "blog"
  weight = 3